name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: /usr/local/Homebrew/Library/Homebrew/vendor/bundle
          key: ${{ runner.os }}-homebrew-${{ hashFiles('/usr/local/Homebrew/Library/Homebrew/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-homebrew-
      - name: Check for conformance to Homebrew style guidelines
        run: brew style Formula --debug
